#!/usr/bin/env python3
#
# Copyright 2015 Michael Terry
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

f = open(sys.argv[1])

rows = 0
cols = 0
goal = ""
words = f.readline().strip().split(" ")
while True:
    if len(words) > 1 and words[0] == "height":
        rows = int(words[1])
    if len(words) > 1 and words[0] == "width":
        cols = int(words[1])
    if len(words) > 1 and words[0] == "goal":
        goal = words[1][1:-1]
    line = f.readline()
    if not line:
        break
    words = line.strip().split(" ")

print("P1")
print(cols, rows)
for y in range(rows):
    line = ""
    for x in range(cols):
        line += goal[cols * y + x] + " "
    print(line.strip())
